### ISSUE TITLE
`back` browser action is broken for measurements webpage

### ISSUE THREAD

**Issue by darkk** [TheTorProject/ooni-wui#14]
1. Fire up fresh ooni-probe-2.0.0 VM/container & go through quiz
2. run `ooniprobe-agent stop && oniprobe-agent start` to trigger the scheduler (will be fixed in TheTorProject/ooni-probe#631)
3. Go to http://172.17.0.2:8842/client/#/measurement
4. Click `Show measurement` button for `vanilla_tor` or `http_*` tests (`web_connectivity` is not affected)
   4½. The browser is redirected to `http://172.17.0.2:8842/client/#/measurement/${id}-vanilla_tor` followed by redirect to `http://172.17.0.2:8842/client/#/measurement/${id}-vanilla_tor/0`
5. Browser `Back` button is broken, it redirects to `…/${id}-vanilla_tor` that is redirecting back to `…/0`

Right-clicking the Back button to get two pages back works.

`…/${id}-vanilla_tor` may use history API to get cleaner redirection, `#measurement` may redirect directly to `…/0`, maybe there are better ways to fix that.

**Comment by hellais** [comment]
Yes I can confirm this is indeed a bug. Thanks for filing a ticket on it.

This is due to the fact that when we detect a single entry measurement we bypass the intermediate page and trigger a redirect to the final page.

I agree that the HTML5 history API to overcome this (possibly this would also clean up the URLs a bit), but need to think a bit about what would be the consequences of that and if there is a better fix.

**Comment by hellais** [comment]
This should no longer be relevant
